### ISSUE TITLE
[Toggle  Expanders] doesn't work with Show/Hide resolved

### ISSUE THREAD

**Issue by aspiers** [Mottie/GitHub-userscripts#100]
I was pretty sure that Shift+click and Control+Shift+click on Show/Hide resolved expanders in PRs used to work, but it certainly doesn't work for me now - it just behaves like a normal click without Shift or Control.  Here's an example I used to test: https://github.com/crowbar/crowbar-core/pull/1853

**Comment by Mottie** [comment]
Hi @aspiers!

Thanks, I'll take a look this weekend.

**Comment by Mottie** [comment]
Hmm, did they get rid of the outdated toggle? I think it was renamed to show/hide resolved and outdated was moved to a label inside the block.

**Comment by aspiers** [comment]
Yes that's right I think.

**Comment by Mottie** [comment]
Please try out the latest version.

**Comment by aspiers** [comment]
Works perfectly now, many thanks!
