### ISSUE TITLE
GitHub table of contents position issue when viewport is resized

### ISSUE THREAD

**Issue by mxmilkb** [Mottie/GitHub-userscripts#102]
I'm using the TreeStyleTabs addon sidebar. When I toggle the sidebar off, the position of the ToC doesn't change. This is also the case when the whole window is resized.

**Comment by Mottie** [comment]
Hi @mxmilkb!

I'm guessing you mean [this Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/)? I'm not sure what you mean by the position of the TOC not changing. If it ever goes off screen you can reset it using the <kbd>g</kbd>, then <kbd>r</kbd> hot keys.

The popup is draggable, and it's position is set from the left side of the window. Do you think if we saved the distance from the right edge of the window that it would behave more as you would expect?

**Comment by mxmilkb** [comment]
Yes. As in, when the viewport width increases, the menu then overlaps part of the central content.

Thanks for the tip! I've remapped these to c+i and c+a so as to avoid keys used by Vimium or Github. This changes the molehill of a problem from a minor practical issue to an aesthetic one :)

Indeed, I was wondering if there was a way to have it position itself relative to the edge of the central content.

**Comment by Mottie** [comment]
Please try out the latest version. You'll likely have to reset the popup, but now it will maintain it's position based on the middle of the screen. That was a great idea! Thanks!

**Comment by mxmilkb** [comment]
That's great, thanks!

The title of the popup does say 'null' though.

Aside; when I restore the popup, it's position moves to just below the header, rather than the default position.

**Comment by Mottie** [comment]
The title can be modified through the Tampermonkey settings.

Yeah, I made the default/reset position of the popup to be in the upper right under the header. Move as desired.

**Comment by mxmilkb** [comment]
`title: "Table of Contents",` was already set at the top of the script.

I selected the Tampermonkey menu item "Set Table of Content Title", then entered "Table of Contents", and I got this;

![image](https://user-images.githubusercontent.com/108225/64197379-dc135880-ce7d-11e9-9f97-98afa9f5c04b.png)

**Comment by mxmilkb** [comment]
Hmm, it appears to have ironed itself out now, I'm just seeing "Table of Contents" as the title now. I had thought I'd done a hard rereload before..

**Comment by Mottie** [comment]
I was able to duplicate the issue... I'll investigate soon.

**Comment by Mottie** [comment]
Ok, all fixed now! 🎉
