### ISSUE TITLE
[GitHub Custom Hotkeys] Firefox's search-as-you-type breaks shortcuts

### ISSUE THREAD

**Issue by monk-time** [Mottie/GitHub-userscripts#103]
Hi!

I'm using Firefox 70 with Tampermonkey and the option "Search for text when you start typing" turned on. As long as it's enabled, all shortcuts defined in "GitHub Custom Hotkeys" (such as "g h") fail as they get intercepted by the search bar.

It used to work several months ago, so probably something has changed on the Firefox's end.

**Comment by Mottie** [comment]
Hi @monk-time!

This userscript uses the same method that GitHub uses to add hotkeys. And I would think that any browser set option to intercept typing would override anything we could do in a website. I've never tested that interaction before, I didn't know that it use to even work.

Anyway, sorry, there isn't much I can do from my end. You might want to submit a report to Firefox, unless GitHub changed things recently that I didn't know about.

**Comment by monk-time** [comment]
Duh, I completely forgot that Github has its own hotkeys. And they too no longer work too with this option enabled. So yeah, sorry for a false alarm, the issue comes from somewhere between GH and FF. I'll try to investigate it further!
