### ISSUE TITLE
Collapse all / expand level / expand all buttons?

### ISSUE THREAD

**Issue by mxmilkb** [Mottie/GitHub-userscripts#108]
Soulseek has this functionality when browsing a library, where everything is expanded by default but there are buttons that collapse all to see just the root level then progressively 'unfold' the menu.

**Comment by Mottie** [comment]
Hi @mxmilkb!

Collapse & expand content on what page?

This repo already has userscripts for:
- [collapsing markdown by header](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-collapse-markdown)
- [repo files filter](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-files-filter)
- [code folding](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-folding)
- [collapsing long code/quote blocks](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-collapse-in-comment)
- [diff files filter](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-diff-files-filter)
- [toggle expanders](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-toggle-expanders) like on the commits page

Please share a link to the page with content to which you are referring.

**Comment by mxmilkb** [comment]
Oop, sorry, the ToC plugin

**Comment by Mottie** [comment]
Oh, you can already do that... 

> <kbd>Shift</kbd>+ Click on the arrow next to the anchor to toggle all same level items.

from the docs - https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-table-of-contents

**Comment by Mottie** [comment]
Maybe not _exactly_ what you're looking for, but it's served me really well. I am open to feedback on how it could be improved.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by Korb** [comment]
> * [toggle expanders](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-toggle-expanders) like on the commits page

Unfortunately, despite the documentation of `GitHub toggle expanders` stating

> A userscript that toggles all expanders when one expander is shift-clicked

it does not work on the User's Contribution activity page (Overview tab).

@Mottie, can you consider creating a corresponding userscript?
