### ISSUE TITLE
GitHub Toggle Diff Comments stopped working

### ISSUE THREAD

**Issue by sfdye** [Mottie/GitHub-userscripts#109]
- Each comment block now has a clickable toggle arrow in the upper right corner. (this is now gone)
- Use Shift + click to collapse or expand all comment blocks on the page. (does not work anymore)
- Use Shift + click to show or completely hide all the comment blocks in the file. (Does not work anymore)

**Comment by Mottie** [comment]
Hi @sfdye!

I meant to finish this fix over this weekend. It was a bit more of a complicated fix than I anticipated, but it's something I'm still actively working on. I didn't want to hold up the other work, so it wasn't included in the latest release.

**Comment by sfdye** [comment]
No worries, take your time :)

**Comment by fuzzyami** [comment]
comments. comments everywhere. would love to see this fixed. thanks!

**Comment by Mottie** [comment]
Sorry for the long wait!

**Comment by fuzzyami** [comment]
thanks so much!
