### ISSUE TITLE
[GitHub Custom Navigation] This style seems broken due to Github update

### ISSUE THREAD

**Issue by Rupthya** [Mottie/GitHub-userscripts#110]
I just guessing its broken due to Github update

https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-custom-navigation

Now it look like this

![Img](https://i.imgur.com/IGCn1lE.png)

Thanks for your help

**Comment by Mottie** [comment]
Hi @Rupthya!

Thanks for reporting this issue!
