### ISSUE TITLE
(GitHub diff files filter) Only «all» button seems to do anything

### ISSUE THREAD

**Issue by daaain** [Mottie/GitHub-userscripts#113]
I installed the `GitHub diff files filter` on Firefox with Tampermonkey.

When looking at a PR all the buttons are correctly rendered (ie file extensions and folders are picked up), but toggling anything other than the `«all»` button doesn't do anything.

How can I debug it?

**Comment by Mottie** [comment]
Hi @daaain!

Hmm, yeah that seems to have stopped working. I probably won't be able to work on this until the weekend.

As for debugging... it looks like GitHub removed the file anchors which were being used to target the file blocks - see https://github.com/Mottie/GitHub-userscripts/blob/master/github-diff-files-filter.user.js#L75. The userscript is using the unique SHA to target each file. It looks like it could be switched to the div id instead.

**Comment by daaain** [comment]
Yes, this works!

```
group.forEach(file_div_id => {
	const file = $(`#${file_div_id}`, files);
	if (file) {
		file.classList.toggle(`gdf-${subgroup}-hidden`, !show);
	}
});
```
