### ISSUE TITLE
It seems github-rtl-comments is not working anymore

### ISSUE THREAD

**Issue by worldsnas** [Mottie/GitHub-userscripts#114]
I tried to install [Github RTL comments](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-rtl-comments) using [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) on firefox.

But I don't see the button on any comment.

I'm not a Javascript developer or I would check it out myself.

**Comment by Mottie** [comment]
Hi @worldsnas!

Thanks for letting me know! I've got a busy week planned ahead, and a few other userscripts that have broken with the new GitHub design. I'll see what I can do this coming weekend.

**Comment by Mottie** [comment]
So I figured out that the problem is that the userscript did not support GreasyMonkey v4 (like most of my userscripts), but I went ahead and updated it to work.
