### ISSUE TITLE
GitHub image preview adds an additional "exploregrid-item image m-3 float-left js-navigation-open" class inside the dropdown-menu "get-repo.modal" div class.

### ISSUE THREAD

**Issue by TheWAVs** [Mottie/GitHub-userscripts#116]
Hi!, I figured out the script adds an additional **"exploregrid-item image m-3 float-left js-navigation-open"** class inside the "Code" dropdown menu whenever I click on either the button "Show tiled files with image preview" or the button "Show full width files with image preview", so it mess up the dropdown-menu "Download zip" section.

**_Proof:_**

![twblpttpMg](https://user-images.githubusercontent.com/10777531/87245265-54ef2380-c444-11ea-9c5a-101874917f83.gif)

Could you fix this awful issue? 🤔

**Comment by Mottie** [comment]
Hi @TheWAVs!

Thanks for reporting this problem. It's just been fixed. Please note that GreasyFork isn't updating the userscript as expected, so please install from here on GitHub or OpenUserJS. Thanks!
