### ISSUE TITLE
a Bug for  `GitHub-table-of-contents` Script

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#117]
https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-table-of-contents
https://greasyfork.org/scripts/18344

This script is excellent and practical.

But when **Enable**  Chrome built-in **translation**, there is no response to clicking on Toc, **can't** jump to Toc location.

Please see the address bar, URL of ⚓#anchor(URL-hash)  will not change automatically,
so, it can not jump to Toc location.

![bug](https://user-images.githubusercontent.com/10995302/87693054-13050b00-c7bf-11ea-8f85-449850352751.gif)

can you fixed it

**Comment by Mottie** [comment]
Hi @dnknn!

Hmm, it looks like Google translate breaks the links by adding an unclickable `<font>` element inside the links. I think I have a fix. Let me know if it works for you.

**Comment by dnknn** [comment]
Hi:) @Mottie 
👍You are so clever, perfect with one 🅲🆂🆂

`.ghus-toc li a font {pointer-events:none}`
Plus this can indeed penetrate to click on the <a> link.
This is a flaw in Google Translate

Perfect, thanks a lot again @Mottie ❣
