### ISSUE TITLE
 can double-clicking to hide ? for `GitHub-table-of-contents` Script

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#118]
If easy to achieve, Can you add `double-clicking` to hide `Toc` ?

Please see the screenshot below ❸:

![Pic-200723_756](https://user-images.githubusercontent.com/10995302/88240575-11a17a00-ccba-11ea-9c36-2408912b8666.png)

**Comment by Mottie** [comment]
Hi @dnknn!

That's an easy enhancement to make. I'll make it available soon.

**Comment by Mottie** [comment]
Hmm, weird. I just noticed that the double-click only works after you drag & drop.

**Comment by Mottie** [comment]
Ok, fixed. There is a delay after the double-click before the window collapses; I haven't spent too much time investigating how to fix that while also trying to detect a drag & drop.

**Comment by dnknn** [comment]
I tried it, and it was perfect, no problem.
Thanks you very much!
