### ISSUE TITLE
Copy code snippet button background is blue

### ISSUE THREAD

**Issue by TheBestPessimist** [Mottie/GitHub-userscripts#119]
In the wiki page, the gif shows the button as white: https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-copy-code-snippet.

In my system however, the button has a blue background, because of the `btn-blue` class here: https://github.com/Mottie/GitHub-userscripts/blob/master/github-copy-code-snippet.user.js#L25

![image](https://user-images.githubusercontent.com/4482210/88258249-5df3b680-ccc8-11ea-9faf-abf4f5fd0f1f.png)

If i remove that class, the button looks like in the wiki preview.

Would you consider removing that blue background?

----

If needed, I'm using violent monkey in firefox and chrome and they both show the blue background.

**Comment by Mottie** [comment]
Hi @TheBestPessimist!

Wow, I don't remember why I made that blue 😆

I'll get that fixed here shortly. Thanks for letting me know!
