### ISSUE TITLE
Can: Open in new tab ? for GitHub custom hotkeys

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#123]
Thanks for this tool, it is very easy to use!  
![208_07115543](https://user-images.githubusercontent.com/10995302/89607365-f1221400-d8a4-11ea-9bf3-9d6f0e59f369.png)

- ### 💥 Current issues: 
Can only be opened in the current tab.

- ### ❥ Expected behavior: 
Some lists can be opened in a new tab.

- ### ❓ How to achieve: 
Add a checkbox to each list : ⬜ or 🔲 or 🗔   

Or, edit in `JSON`.

**Comment by Mottie** [comment]
Hi @dnknn!

This userscript uses GitHub's built-in [hotkey code](https://github.com/github/hotkey), and after looking through their documentation & code, I didn't see any way to make it open a page in a new tab. I'd recommend that you open an issue in that repo to get a discussion started on this enhancement.

**Comment by dnknn** [comment]
Thanks♪(･ω･)ﾉ

**Comment by Mottie** [comment]
Oh, I see... so the link just needs a `target`... I'll see what I can do.

**Comment by dnknn** [comment]
Very, it works perfectly.
