### ISSUE TITLE
github-toc.user.js toc includes side panel headings

### ISSUE THREAD

**Issue by mxmilkiib** [Mottie/GitHub-userscripts#124]
Such as on https://github.com/mixxxdj/mixxx/wiki/midi%20scripting

![image](https://user-images.githubusercontent.com/108225/89690821-586cb200-d8ff-11ea-8a75-879157b15ece.png)

**Comment by Mottie** [comment]
Hi @mxmilkiib!

Thanks for reporting this problem! I'll get it fixed soon.
