### ISSUE TITLE
Bugs for `GitHub custom hotkeys`

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#125]
Hi @Mottie !
Thanks for the release of version 1.1.0, optional to open in new tab, working perfectly by itself..
But other have a bug, 

![208_10200541](https://user-images.githubusercontent.com/10995302/89780914-eab1c780-db44-11ea-9035-5350e5587f06.png)

1. Then, On the any page, can not use `g q` to popup this dialog box.
https://github.com/........#hotkey-settings

2. On the github homepage, it will also cause the left sidebar to be **deformed**.

https://github.com/#hotkey-settings

![208_10200104](https://user-images.githubusercontent.com/10995302/89780559-3fa10e00-db44-11ea-98b8-b5ac93de3f5b.png)

**Comment by Mottie** [comment]
HI @dnknn!

Hmm, it looks like the github home page does that no matter what bookmark you add to the url, e.g. https://github.com/#blah

**Comment by dnknn** [comment]
You don't seem to understand the specific meaning.


![208_10204232](https://user-images.githubusercontent.com/10995302/89783757-0e2b4100-db4a-11ea-90c2-ffedd4134247.png)

**Comment by Mottie** [comment]
I do understand; but there is something odd going on with that page when you add a hash. I didn't close this issue because I still need to spend time investigating why the settings popup doesn't open.

**Comment by dnknn** [comment]
Ok. The previous version no this problem. can use the hotkey to popup, but now can only use the mouse to click to popup. That's what it means.
