### ISSUE TITLE
Github Toggle Wiki Sidebar broke?

### ISSUE THREAD

**Issue by troychard** [Mottie/GitHub-userscripts#127]
The GitHub Toggle Wiki Sidebar broke for me some time back.

I seem to have fixed it just now on my local machine by altering line 59 from 
`const sidebar = $("#wiki-rightbar"),` to `const sidebar = $(".wiki-rightbar"),`

(Edit: nope, my little hack didn't fix.  It does make the sidebar appear and re-appear, but the rest of the content doesn't stretch to fit when it disappears).

Possible bug?  or maybe I'm just seeing weird behaviour on my local machine?
( Using TamperMonkey with Chrome )

**Comment by Mottie** [comment]
Hi @troychard!

Thanks for letting me know! I don't use the wiki pages as often as I used to, so I didn't notice that it broke.

**Comment by troychard** [comment]
Confirmed, the fix Works!  Thanks Mottie! :D
