### ISSUE TITLE
(GitHub Collapse Markdown) fix for no longer working in Greasemonkey

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#13]
The following is a Firefox/Greasemonkey-only issue: 
in Chrome 53/Tampermonkey 4.1.10 the issue doesn't occur.

_Using GCM v1.1.3 with GM 3.9 in FF 49  (win 10 x64)._

The script was no longer collapsing Markdown in any GitHub page.
To make sure I tried in a fresh FF profile with only GM installed and the script
and opened as a reference https://github.com/sinatra/sinatra 
_(i.e. is the page that you used in the [screen capture](https://cloud.githubusercontent.com/assets/136959/16364748/34f5d776-3bb4-11e6-84c7-a00f2817f80a.gif))_ :
no content was collapsed.

I was getting
```
missing = in const declaration                 GitHub_Collapse_Markdown.user.js:233:13
```
in Browser Console.

So, changing lines 233 and 240 
from
`for (const el of els) {`
to
`for (let el of els) {`
fixes the issue.

**Comment by Mottie** [comment]
Hi @darkred!

Thanks for letting me know! I'll have it fixed in a minute!

Also, in case you didn't know, I'll be going out of town for the next month. So if you don't get a response from me, you'll know why.

**Comment by darkred** [comment]
You're welcome.
And thanks for letting me know, I really appreciate this.
