### ISSUE TITLE
(GitHub Toggle Expanders) Shift+Click (toggle all expanders within a date block) not working in repo commit pages

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#131]
Hi there @Mottie .

I've tried 'GitHub Toggle Expanders' in repository commit pages
and unfortunately <kbd>Shift + Click</kbd> (*toggle all expanders within a date block*, e.g. a commit in Dec 17, 2020) doesn't toggle any other expanders but the current one.
There's no error in Console.
(Ctrl + Shift + Click (toggle all expanders on the page) works fine).

Example pages:
https://github.com/mirror/jdownloader/commits/master
https://github.com/torvalds/linux/commits/master

Tested with Tampermonkey/Violentmonkey in Chrome/Firefox.

-----

Also, in the script [wiki](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-toggle-expanders) it says:
> * Toggle expanders (`…`)
>   * Use <kbd>Shift</kbd> + Click on an expander to toggle all expanders within a date block (**New behavior in v2.0.0**)
>   * Use (<kbd>Ctrl</kbd> or <kbd>&#x2318;</kbd>) + <kbd>Shift</kbd> + Click on an expander to toggle *all* expanders on the page (**New behavior in v2.0.0**).

The accompanying [GIF](https://cloud.githubusercontent.com/assets/136959/18611934/23386722-7d10-11e6-81b2-60db18079849.gif) shows that Shift+Click expands *all* expanders in the page, not those within a date block.
So, the GIF depicts the pre v2.0.0 behavior. Could you please also update it?

**Comment by Mottie** [comment]
Thanks! It's fixed now.

**Comment by darkred** [comment]
Thanks a lot for the quick response!
