### ISSUE TITLE
invalid for `GitHub custom hotkeys`

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#133]
<img align=right width=50% src=https://user-images.githubusercontent.com/10995302/106370954-26ae4280-639a-11eb-9ee9-08e7990f491f.png>

- ### I can't see it now, so can't use it at all....
https://greasyfork.org/scripts/18675

**Comment by Mottie** [comment]
Hi @dnknn!

Thanks for reminding me! I had a fix in the works, but forgot to finish it up.

**Comment by Mottie** [comment]
Fixed in https://github.com/Mottie/GitHub-userscripts/commit/5c6902afa8801556517ac6bd536134736fa156ed
