### ISSUE TITLE
which JS for expand all issue and comment ?

### ISSUE THREAD

**Issue by mycal123** [Mottie/GitHub-userscripts#134]

**Comment by darkred** [comment]
There isn't such script.
Mottie has done an excellent work, even categorizing his scripts in the wiki:
https://github.com/Mottie/GitHub-userscripts/wiki

What you're looking for is probably a feature of the Refined GitHub extension:
![2021-02-05_165833](https://user-images.githubusercontent.com/723651/107049988-6bd7d780-67d3-11eb-8f49-29678403cfe8.jpg).
