### ISSUE TITLE
(GitHub Toggle Expanders) When the content is expanded, the expander (`…`) to become dimmed/grayed out

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#135]
Hi there @Mottie

It's a feature request about the 'GitHub Toggle Expanders' script: 
**when any expander (`…`) is clicked (i.e. either manually by the user or via the script's functionality) and the content is expanded, the relevant expander to become dimmed/grayed out.**

I wanted to make this request since forever, but hesitated to ask because the cause is the GitHub layout itself:
currently, when clicking an expander and the content becomes expanded, there's no difference in the expander appearance, and so you can't distinguish the expand status by looking at the expander :

<details>
<summary>screenshot comparison</summary>

*(using the 'GitHub Dark' style)* -the same with GitHub's own dark/light themes - 

![2021-02-10_201041](https://user-images.githubusercontent.com/723651/107552374-19842580-6bdc-11eb-9c31-97030ff7230e.jpg)

![2021-02-10_200921](https://user-images.githubusercontent.com/723651/107552266-e772c380-6bdb-11eb-9e13-ac226aa705d5.jpg)
</details>

Thank you

**Comment by Mottie** [comment]
There really isn't much I can do within the userscript to fix this without messing up the color theme... If you're using the Stylus extension, you could create a GitHub auxillary style and include the following:

```css
.Details--on .ellipsis-expander {
  background: var(--color-scale-blue-2);
}
```

Adjust the color as desired.

**Comment by darkred** [comment]
Thanks a lot! It works great!
