### ISSUE TITLE
hotkey-event-Bug of GitHub custom hotkeys

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#136]
<img align=right width=45% src=https://user-images.githubusercontent.com/10995302/107621108-b86a5980-6c90-11eb-8ee9-2f1f28afc586.png>

For example: 
<table>
<tr>
	<td>t t
	<td>{root}/notifications
</table>

---
Please note that:  I defined two `t` .

`keydown` `t` and `keydown` `t` again, This is normal, no problem.

But if this is the case, the problem/bug is exposed:
`keypress`(e.g. holding⩾100ms) `t` will also trigger, this feels bad.

`keypress` ≠ `keydown` or `keyup`

So, I think that since there are 2 `t` is defined, it should be triggered by pressing 2 times `t`.

---
That means you cannot use `keydown` and  `keypress` at the same time, For example:👇

Linkclump
https://chrome.google.com/webstore/detail/lfpjkncokllnfokkgpkobnkbkmelfefj

![212_11175019](https://user-images.githubusercontent.com/10995302/107621703-a3da9100-6c91-11eb-813b-a0bd79a19ca3.png)

**Comment by Mottie** [comment]
Hi @dnknn!

This userscript manages adding hotkey links to the page within the defined scope. GitHub's [hotkey](https://github.com/github/hotkey) code handles the `keyup`/`keydown` events. Please open an issue in their repo to let them know about the problem. Thanks!

**Comment by dnknn** [comment]
👌

**Comment by dnknn** [comment]
Since github there replied, I also closed this issue, thank you!
