### ISSUE TITLE
Open in the background tab for GitHub Download ZIP

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#139]
[GitHub Download ZIP](https://greasyfork.org/scripts/373514)

![image](https://user-images.githubusercontent.com/10995302/111053861-5fb1fa80-84a2-11eb-8475-6083c176e63f.png)

Usually click on the download `a` link to open in the background, so that it will not affect the tab jumping.

```js
// @grant GM_openInTab

.....
	GM_openInTab();
.....

```

👆 This can be opened in the background

open in the background tab, the current tab will remain motionless (will not jump to the left or right)

**Comment by Mottie** [comment]
Hi @dnknn!

I'm not seeing this happen in Chrome. Which browser are you using?

**Comment by dnknn** [comment]
@Mottie You need to use an extension/script to customize the position where the label opens and closes. If the two are different positions, then the problem I said will occur.

SimpleTabOrder
https://chrome.google.com/webstore/detail/cekafjbmkfofacenifehbglhmajimhjf

Tab Position Customizer - Modified
https://chrome.google.com/webstore/detail/kkhcdbdhbmegbbhgmdhhpfmjhlhjlghp

or [CentBrowser](http://centbrowser.com/history.html#:~:text=64-bit%20Portable)

![image](https://user-images.githubusercontent.com/10995302/111054865-f5ea1e80-84aa-11eb-885c-b1166475559d.png)

**Comment by dnknn** [comment]
Mainly, the link downloads I have seen are all opened in the background tab, not in the foreground.

**Comment by dnknn** [comment]
This issue is very small and will not affect big problems, so it can be closed at any time. I'm just talking about it

**Comment by dnknn** [comment]
This issue is very small and will not affect big problems, so it can be closed at any time. I'm just talking about it ^_^
