### ISSUE TITLE
Can `Copy Code Snippet`  also support to code of greasyfork.org ?

### ISSUE THREAD

**Issue by dnknn** [Mottie/GitHub-userscripts#140]
Hi~ This script is very easy to use and useful, there is a suggestion: 

```
// @include		/https://greasyfork.org/[^/]+/scripts/\d+[^/]+/code/
// @include		/https://sleazyfork.org/[^/]+/scripts/\d+[^/]+/code/
```

For example:  https://greasyfork.org/scripts/37307/code

![image](https://user-images.githubusercontent.com/10995302/111898863-902a0380-8a63-11eb-9dd4-e8dbd6b9428d.png)

**Comment by Mottie** [comment]
This change won't work because the copy code userscript uses the built-in [GitHub Clipboard copy element web component](https://github.com/github/clipboard-copy-element).

Anyway, I added it over in the Misc-userscripts repo - https://github.com/Mottie/Misc-userscripts/wiki/Greasy-Fork-Copy-Code

**Comment by dnknn** [comment]
Thank you so much for your contribution!!!

> https://github.com/Mottie/Misc-userscripts/wiki/Greasy-Fork-Copy-Code#wiki-body:~:text=Click%20this%20link%20to%20install%20from%20GitHub%2C%20or%20install%20from%20GreasyFork%20or%20OpenUserJS

👆 The wrong link points to ^_^

![image](https://user-images.githubusercontent.com/10995302/111922395-7ecd0f80-8ad4-11eb-8689-2238d8d17abc.png)
