### ISSUE TITLE
Is GitHub Enterprise (GHE) supported?

### ISSUE THREAD

**Issue by sql-sith** [Mottie/GitHub-userscripts#143]
And if so, how do I make it work? I just installed `GitHub Copy Snippet` and it works on `github.com` but not on our GHE server.

**Comment by sql-sith** [comment]
I'm not a javascript guy, but I probably should have been able to figure this out before asking here. In case anybody else has the same question, here's what I did to get TamperMonkey scripts to work on our GitHub Enterprise (GHE) repos:

1. Click on the TamperMonkey extension icon and choose Dashboard.
2. Select the userscript you want to enable for GHE by ticking the checkbox on the left. 
3. Click the Edit icon on the right (which is a pencil in front of a square as of this release).
4. Add a wildcard URL for your GHE repos to the comments at the top. For example:
`// @include https://github.my-ghe-server.com/*`.
5. Profit.

**Comment by Mottie** [comment]
Hi @sql-sith!

Instead of modifying the file itself, switch to the "Externals" tab (vs the "Editor") and add your url to the `User includes` section
![2021-04-18 08_29_27-GitHub Code Colors](https://user-images.githubusercontent.com/136959/115147374-51ff1000-a020-11eb-93e5-1fa753e60eb6.png)
