### ISSUE TITLE
All userscripts stop working 

### ISSUE THREAD

**Issue by twio142** [Mottie/GitHub-userscripts#144]
I installed a few userscripts from this repository:
- Custom Navigation
- Hovercard
- Raw Links
- Reveal Header
- Code Folding

They worked just fine till yesterday, but suddenly none of them works anymore and I don't remember changed anything.
Meanwhile, the browser extensions for GitHub (Octotree, Octolinker, Octohint) work just fine.
I'm using TamperMonkey on Chrome 90 on macOS, the extension and the userscripts have been always enabled.
Could it be some settings on github.com??

**Comment by darkred** [comment]
First of all, if a script is no longer working for you, 
if you want to facilitate the script author in helping you, 
it's crucial that you disable ALL other extensions than Tampermonkey/Violentmonkey, or ideally use only TM/VM with a fresh browser profile.
Then test the script as follows: 
- login to github
- enable one script at a time, 
- install/enable your other extensions one by one, to find any conflicts.

---

Secondly, of all, there is no "Hovercard" script in this repo,
Only this issue https://github.com/Mottie/GitHub-userscripts/issues/71 that links to a script in a different repo.

----

Finally, of the remaining 4 scripts you mentioned, I confirm that only one script of those you mentioned no longer works, 
it's 'Gist Raw Links' with test page e.g.: https://gist.github.com/Mottie/91968692d074f93eb9a7
[No error in console.]

All other 3 scripts work fine in a Chrome 90 fresh profile with latest TM beta.

**Comment by twio142** [comment]
Well, I found out it's not just the github userscripts, but the entire tampermonkey extension was not working on my browser, despite always been enabled. Tried toggle it on and off a few times and it's normal again.

Thanks for the reply anyway!
