### ISSUE TITLE
Code-Folding only works when refreshing file

### ISSUE THREAD

**Issue by ACH1980** [Mottie/GitHub-userscripts#146]
Code-Folding works fine, but everytime when I open a new file the functionality isn't there, I need to refresh the file and then it's functioning. The script was loaded on the first loading too but only worked after reloading...

**Comment by JackofSpades707** [comment]
This may be relevant to #153

**Comment by JackofSpades707** [comment]
Looks like the solution is here: https://stackoverflow.com/questions/17862394/my-userscript-only-works-when-the-page-is-refreshed-or-on-iframes-not-the-main
Although this may be dated info

**Comment by ACH1980** [comment]
> This may be relevant to #153
> I can confirm I am experiencing this behavior as well

No, the code is there, but can't be folded...



> Looks like the solution is here: https://stackoverflow.com/questions/17862394/my-userscript-only-works-when-the-page-is-refreshed-or-on-iframes-not-the-main
> Although this may be dated info

I'll have a look, give me a moment...

**Comment by JackofSpades707** [comment]
> > This may be relevant to #153
> > I can confirm I am experiencing this behavior as well
> 
> No, the code is there, but can't be folded...
> 

The core problem is the same, Script X not running until the page is refreshed.

**Comment by ACH1980** [comment]
Yep, seems to be that problem... I don't have an idea how to fix, other then executing the code regularly even if no page was loaded (have done this for several scripts on .io-Games, but it could be a bit to heavy for github Scripts)... Maybe the devs have another idea? I'll close this one as it already exists and will post a summary in the other issue...

**Comment by JackofSpades707** [comment]
It's a good idea to provide a link to this issue as well by typing '#' + Issue number

**Comment by ACH1980** [comment]
Yeah I know and will do so! :)
