### ISSUE TITLE
GitHub copy code snippet - Deprecated

### ISSUE THREAD

**Issue by JackofSpades707** [Mottie/GitHub-userscripts#155]
Github offers this functionality itself now.
[Github copy code snippet](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-copy-code-snippet)

**Comment by darkred** [comment]
Yes, but unfortunately there are still cases where the built-in button is missing, 

examples:
https://github.com/tophf/mpiv/discussions/50#discussioncomment-368271
https://github.com/sindresorhus/refined-github/issues/4337#issuecomment-835842120

**Comment by JackofSpades707** [comment]
Ahhh gotcha, I'll go ahead and close this then

**Comment by JackofSpades707** [comment]
It might be a good idea to move it into the Deprecated section of the Readme, but I'll leave that to you guys to decide.
