### ISSUE TITLE
GitHub diff links "squeezes" triple-dot button

### ISSUE THREAD

**Issue by stdedos** [Mottie/GitHub-userscripts#158]
Actual:
![image](https://user-images.githubusercontent.com/133706/126284412-bb4690eb-e524-4b56-ae8a-7dfbe0b6bab5.png)

With
![image](https://user-images.githubusercontent.com/133706/126284357-8a3593cc-7b08-41b3-8970-3c0064d799a6.png)

gives

![image](https://user-images.githubusercontent.com/133706/126284264-b2def0ec-098f-4c44-8b6d-11c54edcaa4f.png)

**Comment by Mottie** [comment]
Hi @stdedos!

Thanks for reporting this problem. It's just been fixed.
