### ISSUE TITLE
feature request? bug?: GitHub issue comments: support hiding linked commits

### ISSUE THREAD

**Issue by olets** [Mottie/GitHub-userscripts#165]
I'd like to be able to hide linked commits in an issue's activity (e.g. in Issue 1, don't show commits with the message `#1`.

This fits in "GitHub issue comments".

Maybe this is a bug, and the "commits" toggle should be hiding them. Looking at the script I see that toggle is under "pull requests" so maybe the existing toggle isn't targeting issue pages and this is a feature request.

Thanks for all your work on these

**Comment by Mottie** [comment]
Hi @olets!

I'm not sure I understand what you're asking. Do you mean when someone accidentally add `#1` to a comment, you want to unlink it since it's not really a link? I'm not sure we can differentiate them from actual links to tickets?

**Comment by olets** [comment]
Nothing that fancy. I mean hiding all commit references from the issue timeline.

Real life example: this issue has quite a few commits and one comment. The branch was force pushed several times because the project uses a linear commit history and other ongoing work merged. Not a good experience for the project manager who just wants to read the comments.

<img width="200" src="https://user-images.githubusercontent.com/3282350/149188129-6940084f-06e6-4640-ad39-15c699f427d2.png" alt="">

**Comment by Mottie** [comment]
Oh yes, the "commits" toggle should hide all those
![](https://user-images.githubusercontent.com/136959/149250237-e0690a8f-5940-4984-b89c-266003aa2e02.png)

**Comment by olets** [comment]
Hm good to know. It doesn't for me. Maybe I have a conflicting extension. Will look into it…

**Comment by olets** [comment]
Haven't had a chance to debug my environment, but it sounds like this is probably user error. Will reopen if I find that it isn't
