### ISSUE TITLE
Custom navigation formatting on github projects page

### ISSUE THREAD

**Issue by afg1** [Mottie/GitHub-userscripts#169]
For some reason, the custom navigation bar formatting gets messed up on the github projects page:

![image](https://user-images.githubusercontent.com/623671/173778437-8d16344b-67cb-4f6d-9fbe-f8b4e19f47d3.png)

looking at the console, there seems to be something wrong with `ticky-browser.js`

```
ticky-browser.js:8 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'click')
    at openPanel (ticky-browser.js:8:1)
    at openPanelOnHash (ticky-browser.js:8:1)
    at ticky-browser.js:8:1
    at Proxy.tms_f18bf04f_a17d_43d5_9921_24ec53e32b7b$ (ticky-browser.js:8:1)
    at it (<anonymous>:14:1074)
    at _prelude.js:1:1
    at _prelude.js:1:1
    at window.__p__4587594.598558076 (ticky-browser.js:8:1)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)
```

This only happens inside an active project, just going to the projects page (e.g. in this repo) doesn't cause an issue, but if you go to e.g. https://github.com/users/afg1/projects/1 you should see it

I'm using Chrome and tampermonkey v4.16.1 on macOS. I have your custom navigation, code folding and hotkeys userscripts (they're great, thank you!).

**Comment by TFWol** [comment]
I'm seeing the same problem here with the messed up navigation bar. Pretty much breaks navigating projects.
I've had to put in an exclusion for those types of pages until the script is looked at.
`// @exclude     https://github.com/orgs/*/projects/*`

**Comment by Mottie** [comment]
Hiya! Sorry for the delay, please check to verify that this userscript is now working as expected.

**Comment by TFWol** [comment]
Looks like the script's navigation bar is replaced with the native project navigation.
If that's the intended effect then the script is working.

**Comment by Mottie** [comment]
Yes, the top bar would be too tall if both the project and userscript navigation bars were visible

**Comment by TFWol** [comment]
Makes sense. Good to know script is working as designed.

**Comment by afg1** [comment]
Hi, sorry it took me a while to get back to this - the script is now working as expected, thanks for fixing it!
