### ISSUE TITLE
Github Title Notification is broken

### ISSUE THREAD

**Issue by veksha** [Mottie/GitHub-userscripts#170]
it always shows heart even if there is no new notifications present.

**Comment by TFWol** [comment]
I'm having the same problem.
It seems to happen when I'm browsing a repo's Issues.

**Comment by TFWol** [comment]
I was able to make a workaround.
Replace https://github.com/Mottie/GitHub-userscripts/blob/bc9181cd5d17084aa9f226a0a7cfbb0cd4045c1f/github-title-notification.user.js#L30

with:
```js
hasUnread = !mail.hasAttribute("hidden") ? true : false;
```

**Comment by Mottie** [comment]
I got it working with

```js
hasUnread = mail ? !mail.hidden : false;
```

Sorry, lots of personal stuff going on that I haven't had a chance to actually commit this fix.

**Comment by TFWol** [comment]
> I got it working with
> 
> 
> 
> ```js
> 
> hasUnread = mail ? !mail.hidden : false;
> 
> ```
> 
> 
> 
> Sorry, lots of personal stuff going on that I haven't had a chance to actually commit this fix.

No problem, I'm just glad you've made this amazing repo. 

I didn't do a pull request because I knew you'd have a more eloquent way to fix it; I only dabble in JS 🙂

**Comment by TFWol** [comment]
Is it just me or is changing the notification indicator symbol not working?

**Comment by veksha** [comment]
yes, another bug.

**Comment by TFWol** [comment]
Oo, I see why.

Change:
https://github.com/Mottie/GitHub-userscripts/blob/bc9181cd5d17084aa9f226a0a7cfbb0cd4045c1f/github-title-notification.user.js#L52

To:
```js
GM_setValue("indicator", val);
```

Then refresh page

**Comment by veksha** [comment]
nice work, @TFWol ! thank you.
