### ISSUE TITLE
feature request.

### ISSUE THREAD

**Issue by Cologler** [Mottie/GitHub-userscripts#18]
this is my scripts:

https://greasyfork.org/zh-CN/scripts/29107-gist-raw-button

I hope this feature can be add to:

https://greasyfork.org/zh-CN/scripts/29888-gist-raw-links

**Comment by Mottie** [comment]
Hi @Cologler!

The `gist-raw-links` userscript uses GitHub's API to get the raw file urls so it *should* always point to the newest version. But, I don't see a problem with removing the version specific hash from the URL.

**Comment by Cologler** [comment]
@Mottie but when copy the raw url from `gist-raw-links`, and parse to greasyfork.org, it cannot auto update when gist updated.

**Comment by Mottie** [comment]
Ok, v0.1.3 provides the newest raw url.
