### ISSUE TITLE
Open Extension Page is just broken now.

### ISSUE THREAD

**Issue by MikeRich88** [Mottie/GitHub-userscripts#199]
Open Extension Page is just broken now.

Click it, does nothing. Started randomly happening.

Nothing shows in the console when I inspect the pop up but I can't click on the open extension page fake link (actually a button for some reason) and see the console because the pop goes away and the inspector dies.

Safari Version 17.0 (18616.1.27.111.22, 18616)
macOS 13.6 (22G120)
Userscripts Version 4.5.0 (81) - **You need an edit menu in the Userscripts.app, otherwise you can't copy this information as easily.**

Feels like I have been filing bugs all day so I am just really tired of everything right now. Don't close if you can't reproduce, I'll eventually come back. But the whole extension is useless now unless I go manually edit the scripts.

**Comment by Mottie** [comment]
Hi @MikeRich88!

Sorry, which userscript are you having issues with? I apologize for not being responsive & fixing bugs ASAP. Life, and a 5 year old, has kept me busy.

**Comment by MikeRich88** [comment]
I am not having an issue with any userscript

I can't even edit any of them. "Open Extension Page" is broken

<img width="362" alt="image" src="https://github.com/Mottie/GitHub-userscripts/assets/7113073/69182c6d-d1ae-4350-9ef3-ff519b920f27">

**Comment by Mottie** [comment]
A lot of websites have increased security and may be preventing script injection. I don't know is an extension or built-into Safari specifically, but I'd recommend using [Tampermonkey for Safari](https://www.tampermonkey.net/index.php?browser=safari) instead.

**Comment by MikeRich88** [comment]
Again, that's not the issue.

If I go to my own website, which has no such increased security, and click on "Open Extension Page", it doesn't open.

I don't know how to make this any clearer. Do you need a QuickTime video?

**Comment by Mottie** [comment]
The problem you're describing is not related to any of the userscripts within this repo; and I don't know where to find the "Open Extension Page" link. I'm guessing it's build into Safari, or a browser extension I'm not familiar with. Either way, I don't think I can solve your issue.

**Comment by MikeRich88** [comment]
Please accept my apologies. Obviously I have the wrong repo.
