### ISSUE TITLE
(GitHub Toggle Issue Comments) Only 1 (empty) placeholder is displayed instead of the commenters avatars

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#20]
_Using 'GitHub Toggle Issue Comments' script version 1.0.26
with either GM 3.11 in Firefox 53.0.3 (even in clean profile)
or TM 4.2.7 in Chrome 58._

The issue is that no avatars are added under the `Hide Comments from` text:
only 1 (empty) placeholder (i.e. the `<img>` tag for that empty placeholder has `src="undefined"`.)
is displayed instead.

<br>

Here is a screenshot (from an [issue link example](https://github.com/greasemonkey/greasemonkey/issues/2046#issuecomment-304959491) with 12 commenters ) to better show what I mean:

![2017-06-05_211625](https://cloud.githubusercontent.com/assets/723651/26797048/43767fb4-4a34-11e7-85d7-6dd88f6b6cdb.jpg)

There's no error in Browser Console while this happens.
I checked the `addAvatars()` function 
but unfortunately couldn't locate what's the cause of this.

**Comment by Mottie** [comment]
Hi @darkred!

Thanks for reporting this problem. It looks like GitHub moved the avatar class name. I'll get this fixed ASAP!

**Comment by darkred** [comment]
Thank you for the quick fix!
