### ISSUE TITLE
404 in Wiki

### ISSUE THREAD

**Issue by ShalokShalom** [Mottie/GitHub-userscripts#23]
![screenshot_20170630_205754](https://user-images.githubusercontent.com/6344099/27750138-cf34c096-5dd6-11e7-8969-735557a401cf.png)

**Comment by Mottie** [comment]
Hi @ShalokShalom!

Thanks for letting me know... I'll get that fixed.

**Comment by Mottie** [comment]
Updated in https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-custom-navigation/904ad1c5851f2397f3cb022062ee2abcea717e65.
