### ISSUE TITLE
Custom hotkeys don't work on users that partially match reserved names 

### ISSUE THREAD

**Issue by monk-time** [Mottie/GitHub-userscripts#26]
The script for adding custom hotkeys breaks if a repo owner partially matches any of Github's reserved names. For example, hotkeys don't work on [git-for-windows/git](https://github.com/git-for-windows/git) because it has 'windows' in the owner's name.

This seems to be caused by JS testing a regex at all positions in a given string instead of only at the start (even without a global flag):

https://github.com/Mottie/GitHub-userscripts/blob/a591264342744ca39c2708c6baf7a142b0e4c7cf/github-custom-hotkeys.user.js#L56-L80

https://github.com/Mottie/GitHub-userscripts/blob/a591264342744ca39c2708c6baf7a142b0e4c7cf/github-custom-hotkeys.user.js#L98-L102

I think this issue can be safely fixed by surrounding the regex with `^` and `$`.

P.S. Also it seems like the `{me}` scope is always undefined:
 https://github.com/Mottie/GitHub-userscripts/blob/a591264342744ca39c2708c6baf7a142b0e4c7cf/github-custom-hotkeys.user.js#L91-L93

**Comment by Mottie** [comment]
Hi @monk-time!

Thanks for letting me know about this problem. I'll have it fixed soon.
