### ISSUE TITLE
GM_ APIs no longer supported in GM4

### ISSUE THREAD

**Issue by monk-time** [Mottie/GitHub-userscripts#29]
With the recent update to Firefox (FF57, aka Quantum) Greasemonkey devs [have decided to change](http://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html) their API from synchronous functions `GM_*` to async methods of the `GM` object. This means that starting with GM4 (the first version compatible with FF57+) all scripts that used any of those functions will no longer work. 

As an example, your awesome script for GitHub custom hotkeys in FF57+GM4 dies with *"Script error:  ReferenceError: GM_getValue is not defined"* in the console.

A suggested workaround is to include an official [polyfill](https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js) for the old API. Also, I think most of them can be safely replaced with native `fetch` and `localStorage`.

**Comment by Mottie** [comment]
Hi @monk-time!

I plan on adding support via the polyfill. I need some time to catch up with everything since I just returned from a vacation.

**Comment by Mottie** [comment]
Sorry, it's too much work - see https://github.com/greasemonkey/greasemonkey/issues/2787

**Comment by jerone** [comment]
I agree with you @Mottie. It started with GM4 not detecting my 50+ installed UserScripts. GM does not support drag-and-drop installation (after finding GM's installation folder), and TamperMonkey does, so I switched to TM (also because it is available on all other browsers too). My personal feeling is that GM is forcing a new standard to us way to fast without being backwards-compatible (while TM is forwards-compatible (GM3 + GM4 style)). I only need to update documentation that GM4 is not supported for my UserScripts.

**Comment by monk-time** [comment]
I'm sorry that the GM devs treated your suggestions that way, looks like it's not a happy situation re: GM4 for everybody involved. 

In any case, I've made GitHub Custom Hotkeys GM4-compatible by [switching to native APIs](https://github.com/monk-time/userscripts/commit/80e1bcea8f3c5272ab7eb2edef48115fe314d6a6#diff-da9d1fbe1fc6b540b25d25fa6b09567e) in my fork, but I haven't added any code for user data migration, so I am not sure whether it would make sense to send a PR or not. 

And thank you once again for your scripts! They are immensely helpful.

**Comment by Mottie** [comment]
@monk-time That'll work too... in your fork, make sure to:

* Add `@grant none`
* Change the `@updateURL` and `@downloadURL` to point to your version.

**Comment by monk-time** [comment]
I left it that way to have a minimal PR in case you'd want to integrate those changes, but I'll make sure to add your suggestions. Thanks!

**Comment by Mottie** [comment]
I haven't been using local storage mostly because it may be cleared out by the site ([ref](https://stackoverflow.com/questions/15730216/how-where-to-store-data-in-a-chrome-tampermonkey-script)). 

Oh, I will need to update the custom hotkey script as I found a couple of minor issues...

**Comment by Mottie** [comment]
More GM4 polyfill troubles... https://github.com/JasonBarnabe/greasyfork/issues/523
