### ISSUE TITLE
F1 doesn't work

### ISSUE THREAD

**Issue by myshov** [Mottie/GitHub-userscripts#3]
Hello!
I've tried to setup plugin but no luck.
In the help it said that: "Open the settings panel by pressing "F1" (default setting)"
But f1 doesn't work. I've tried via greasemonkey in Firefox and tempermonkey in Chrome.

I've tried to change "f1" onto "g h" directly in code of script, but It didn't work.

OS: Mac OS X 10.11
All browsers (Firefox, Chrome) are latest version.

**Comment by Mottie** [comment]
Hi @myshov!

DOH, it looks like the default settings are messed up. I'll have the script fixed here shortly. But you can still open the panel by clicking on your avatar and clicking on the "GitHub Hotkey Settings" link.

![2016-07-22 07_05_01-github custom hotkeys mottie_github-userscripts wiki](https://cloud.githubusercontent.com/assets/136959/17056714/c61b1902-4fda-11e6-9136-d8cd5ef22ead.png)

Then [edit the JSON](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-custom-hotkeys#add-or-edit-json), and replace it with this:

```js
{
  "all": [
    { "f1" : "#hotkey-settings" }
  ]
}
```

Or, trigger a factory reset on the userscript (Chrome only, I think).

**Comment by myshov** [comment]
@Mottie Thank you!
