### ISSUE TITLE
request: collapse inline PR comments

### ISSUE THREAD

**Issue by olets** [Mottie/GitHub-userscripts#30]
I'd love a toggle to collapse inline comments in the files view of a PR, with a "toggle all" button and individual toggles on each comment.

Use case: for PRs that are complicated or need a bunch of background knowledge, my team likes to sprinkle in explanatory comments to help reviewers… but that can make the PR look intimidating, and can make reviewing harder for people who don't need the explanations.

Presumably not a small project. I'd be happy to donate towards this

Thanks for all the great tools!

**Comment by Mottie** [comment]
Hi @olets!

I'm glad you're finding the scripts useful! 😸

Have you tried the [issue comments](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-issue-comments) userscript? It has toggles for reviews and diff comments, both current and outdated.

![](https://user-images.githubusercontent.com/136959/33386295-46176e62-d4f0-11e7-939f-af258d8d369f.gif)

Or do you mean replace the ugly comment checkbox that allows you to hide individual comments when on the files tab? And maybe make <kbd>Shift</kbd>+Click toggle them all?

![](https://user-images.githubusercontent.com/136959/33386574-db63b75a-d4f0-11e7-9fa7-22794969b43d.png)

**Comment by olets** [comment]
Oh sweet, no I didn't try it because of

```
It only works on issue comment pages.
```

Will give it a try!

**Comment by Mottie** [comment]
Oops! I've just fixed that message.

**Comment by olets** [comment]
Ok tried it out. Yes, that does exactly what I wanted in the Conversation tab 🎉 

For the Files tab, I don't think I ever noticed the Show Comments check box! How surprising. Looking at it now:

- Yes, I'd love to be able to shift-click to toggle them all.
- Hidden comments are _completely_ hidden. I'd much rather have them collapsed than fully hidden. Maybe the "Show Comments" checkbox could be replaced with a "Collapse Comments" checkbox? Or `Comments: Show | Collapse | Hide` styled to match your diff files filter?
- That check box only shows on files that have comments. It'd be cool to have a button at the top of the page (maybe near `Unified | Split`?) to set the checkbox state for every file

What do you think?

**Comment by Mottie** [comment]
All done. Let me know what you think.
