### ISSUE TITLE
Whitespace toggle not present on all files in diff

### ISSUE THREAD

**Issue by colin-marshall** [Mottie/GitHub-userscripts#33]
I'm using `github-code-show-whitespace.user.js` and Tampermonkey with Chrome 62 on macOS. That's the only script I'm currently using.

In [this diff](https://github.com/olefredrik/FoundationPress/pull/1178/files) I stop getting the toggle button at `library/cleanup.php` and all the files below it.

<img width="1422" alt="screen shot 2017-12-04 at 10 34 00 pm" src="https://user-images.githubusercontent.com/4453733/33591560-67b89cc4-d943-11e7-955e-94226aa2bfe1.png">

**Comment by Mottie** [comment]
Hi @colin-marshall!

Thanks for reporting this problem. It looks like that since the userscript is set to run on document idle and the `@require` code listens for a document ready, it isn't being run.

I'll update the mutations.js file and the show whitespace userscript soon!

**Comment by colin-marshall** [comment]
@Mottie wow that was fast! Just tested and the toggles now go down to the last file. Thanks!!!
