### ISSUE TITLE
Can't move Github Project cards when GitHub code show whitespace is active

### ISSUE THREAD

**Issue by colin-marshall** [Mottie/GitHub-userscripts#36]
Whenever I have the GitHub code show whitespace active, I cannot move cards between columns in GitHub projects.

**Comment by Mottie** [comment]
Hi @colin-marshall!

Hmm, that's very odd. I think it has something to do with with `@grant` setting and maybe GitHub's CSP.

I can break the drag-and-drop on the project page with this minimal userscript:

```js
// ==UserScript==
// @name        test
// @version     1.0.0
// @include     https://github.com/*
// @grant       GM_addStyle
// ==/UserScript==
console.log(document.readyState);
```

And, if I change the `@grant` setting to `none`, the project page starts working. I've only tested this on Tampermonkey Beta for Chrome so far. I'm tired, so I'll test it some more in the morning.

**Comment by Mottie** [comment]
Related: https://github.com/StylishThemes/GitHub-Dark/issues/581 (GitHub-Dark script)

**Comment by Mottie** [comment]
It looks like this has been fixed in Tampermonkey Beta.

**Comment by colin-marshall** [comment]
@Mottie sorry for being slow to respond. Thanks for looking into this and staying on top it!

**Comment by Mottie** [comment]
Tampermonkey v4.6 is now available... closing this issue.
