### ISSUE TITLE
(GitHub Sort Reactions) Suggestion: collapse out of view the block of buttons when mouseaway. In such case, display the active sort icon next to the two-triangles icon

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#39]
@Mottie First of all, thanks a lot for this great script! 
I was wondering whether it's possible to make a script to sort the comments based on the reactions in a practical way ! You really nailed it, once again! 👏 

----

I just have one suggestion, please:

Currently, having two rows of button blocks (one of the post itself and the second by the script)
makes it distracting and difficult for me to visually distinguish them.

My suggestion is to collapse out of view _(- in a similar way to that of your script "GitHub Reveal Header"- maybe collapse  the block by temporarily converting it to a thin line/separator)_ the block of buttons on mouseaway from that element. And: 
- when a sort button is active and the block of buttons is collapsed on mouseaway, 
to display the currently active sort icon and its order (i.e. create an extra icon) next to the two-triangles icon. 
- when no sort is active, remove that extra icon.

Please see my mockup below to better see what I mean.

_I know the script in it's initial version - I just wanted to post my suggestion and I hope you like it._ 🙂

Example screenshot:
![2018-02-28_193405](https://user-images.githubusercontent.com/723651/36802764-7882ff22-1cbe-11e8-8baa-7160863e216b.jpg)
And a mockup:
![2018-02-28_194332](https://user-images.githubusercontent.com/723651/36805200-7838e9da-1cc5-11e8-83e5-1a8e76b604fe.jpg)

<sup>PS. I've tried implementing my suggestion myself but unfortunately it seems too difficult for me, that's why I didn't provide a PR instead.</sup>

**Comment by Mottie** [comment]
Hi @darkred!

Yeah, I agree that having the bar under the comment with all the reactions is a bit confusing. Too many emojis clumped together!

I'm not sure I want to make the bar collapsible. Maybe instead we could do something like this?

![](https://user-images.githubusercontent.com/136959/36811643-1db43054-1c94-11e8-931b-47486ab195b0.png)

Clicking the emoji would open a select showing all reactions. Clicking the arrow would change the sort direction, or remove the sort on the third click.

**Comment by darkred** [comment]
Great idea, @Mottie! That would be the best! Compact and subtle.

**Comment by Mottie** [comment]
Try this out:

![](https://user-images.githubusercontent.com/136959/37052861-373a814e-2140-11e8-92f9-5c6fb57de7ba.gif)

**Comment by darkred** [comment]
Great! Thank you.
