### ISSUE TITLE
(GitHub Custom Navigation) Slight truncation in the icons' left side

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#4]
Thanks for another great userscript!

I just noticed this minor issue:  _(using GCN 1.0.3 in FF48 x64 in win10 with GM 3.8)_
there's a slight truncation in the icons' left side.

Here is a (resized) screenshot where I highlight the truncation (it's a few pixels) :
_-using a clean FF profile with only (GM and) GCN-_
![2016-08-10_223653 2](https://cloud.githubusercontent.com/assets/723651/17569133/98277bba-5f4f-11e6-804c-253247a54dde.jpg)
And here is when the truncation doesn't occur:
![20151010-5f4f-11e6-80b0-82a17c9bcd70](https://cloud.githubusercontent.com/assets/723651/17569224/f668fbf4-5f4f-11e6-9677-c21ff3b20484.jpg)

It occurs in e,g,
https://github.com/
https://github.com/Mottie/GitHub-userscripts

It doesn't occur:
https://github.com/greasemonkey
https://github.com/greasemonkey/greasemonkey/wiki

Having unread notifications (i.e. having the dot on the bell icon) or not, doesn't make a difference.,

**Comment by Mottie** [comment]
Hi @darkred!

Interesting, it seems GitHub has an overflow hidden setting on the svgs. I'll override that in the script. Please let me know if the change fixes the problem.

**Comment by darkred** [comment]
Yes, it's fixed. Thanks for the quick response!

**Comment by darkred** [comment]
Today (probably after some GitHub layout change)
the issue unfortunately occurs again.

It occurs as before in e,g,
https://github.com/
https://github.com/Mottie/GitHub-userscripts.

**Comment by Mottie** [comment]
It does look like the overflow is set again, I just need to increase the specificity. Thanks for letting me know!

**Comment by Mottie** [comment]
Please try the update.

**Comment by darkred** [comment]
It's fixed. Thank you.
