### ISSUE TITLE
(GitHub Sort Content) Add gitlab.com support for sorting markdown tables

### ISSUE THREAD

**Issue by haraldreingruber** [Mottie/GitHub-userscripts#40]
How much effort is it to make the GitHub Sort Content script also work for gitlab.com markdown tables?

I would also consider contributing the enhancement myself. I guess once I figured out the difference compared to the github.com markdown rendering it should not be very difficult.
Just adding the @include rule is not enough, I've already tried that.

**Comment by Mottie** [comment]
Hi @haraldreingruber!

Since I haven't been using GitLab that much, I'll need your help locating more content to make sortable.

I threw together a userscript - https://gitlab.com/Mottie/GitLab-userscripts/wikis/GitLab-sort-content

Right now it'll sort the repo file list and any markdown tables. Please let me know if it ever stops working and what content would be good to add.

**Comment by haraldreingruber** [comment]
Thanks a lot @Mottie!
Unfortunately, the link above doesn't seem to have public access permissions.

**Comment by Mottie** [comment]
You need to log into GitLab to see the repository for some reason... I made it public, so I'm not sure why this is the case.

**Comment by haraldreingruber** [comment]
Thanks. I've changed the Gitlab repo, wiki, issue-tracker, etc. to public... I tested it without being logged in, and also with another user which is not a member of the project.  After a first quick test it looks like write access is only for project members, or via merge-request. Will check the permissions more extensively later this evening. (I only used gitlab with private repos so far).

**Comment by Mottie** [comment]
So weird... I'm sure I saw the setting and it was set to public. I guess I should RTFM.😸

**Comment by haraldreingruber** [comment]
Yeah, there is a setting for the project itself, but then there are also the ones per feature... I think that was causing the confusion.

**Comment by haraldreingruber** [comment]
Cool, it works quite nicely. Thanks for the super fast response 😄 👍
