### ISSUE TITLE
(GitHub Issue Highlighter) The linked-to comment is not highlighted in some cases

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#41]
STR
In a clean Chrome 65 profile with only Tampermonkey 4.6.5752 beta installed and GIH script v1.0.7,
open `https://github.com/gorhill/uBlock/issues/3689` and follow the '#3680 (comment)' link inside the comment:  
the linked-to comment in the target page won't be highlighted.
There's no error in Console.

PS. For reference, for other links to comments, such as the one displayed in the [script info page gif](https://cloud.githubusercontent.com/assets/136959/15451464/3bd4b748-1f89-11e6-81a6-50bd6ed0a3fb.gif): i.e. the comment link inside the 1st comment in `https://github.com/isaacs/github/issues/665`, 
the script still works ok.

**Comment by Mottie** [comment]
Hi @darkred!

Thanks for letting me know. I'll have this fixed soon.

**Comment by Mottie** [comment]
Fixed in https://github.com/Mottie/GitHub-userscripts/commit/75f27e0d0f845aee2930405dd2cee0112417488f.

**Comment by darkred** [comment]
Thanks a lot for the quick fix, @Mottie !
