### ISSUE TITLE
(GitHub Sort Reactions) Third click on 'sort by +1' and 'speak no evil monkey' avatar icons doesn't restore the comment order in some cases

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#42]
STR
In a clean Chrome 65 profile with only Tampermonkey 4.6.5752 beta installed and GSR script v0.2.2:

### case 1
open `https://github.com/gorhill/uMatrix/issues/928` and click on the  'speak no evil monkey' avatar sort icon 3 times: notice that the comment order is not restored.
_With all other avatar sort icons, the comment order is restored ok._

### cases 2, 3
In `https://github.com/gorhill/uMatrix/issues/968` or `https://github.com/gorhill/uMatrix/issues/567`, 
if you click  3 times either the 'speak no evil monkey' avatar icon or the 'sort by +1' avatar icon , the initial comment order is not restored.
_With the other avatar sort icons, the comment order is restored ok._

**Comment by Mottie** [comment]
Hi @darkred!

Eww yuck! Thanks for reporting this problem. I'll try to look into it soon.

**Comment by Mottie** [comment]
Hmmm, ok I'll take a look again.

**Comment by Mottie** [comment]
Sorry for taking so long to get this fixed!

**Comment by darkred** [comment]
Np! Thanks a lot for fixing this!
