### ISSUE TITLE
(GitHub Toggle Issue Comments) check mark hiding comments is unintuitive UI

### ISSUE THREAD

**Issue by aspiers** [Mottie/GitHub-userscripts#44]
The Toggle Issue Comments userscript doesn't hide comments by default, which makes perfect sense.  However the check mark (tick) symbol only appears to the right of a category after clicking a category of comment to *hide* that category, which I find very unintuitive and in fact the exact opposite of what I'd expect.

For example if `Reviews (outdated)` has a check mark next to it, it is more logical to expect that outdated reviews would be displayed rather than hidden, because check marks universally have a positive connotation.  The only category of comment which gets this right is `Hide +1s`, because it makes it clear that when you select that category, the comments are hidden rather than displayed.  

A similar problem is that the categories are emboldened when selected, and again except for `Hide +1s` this is counter-intuitive. 

So I'd suggest one of two things:

1. Prefix every category with `Hide `, *or*
2. Swap the behaviour so that when the category is *displayed* (not hidden) the font is bold and the check marks are displayed, and Rename `Hide +1s` to `+1 comments`.

The first is slightly ugly, but the second could confuse some people who already adapted to the existing behaviour.  Pick your poison, or maybe come up with a third approach which has neither of these problems ;-)  Either way, I really think it needs to be made more intuitive, and the inconsistency between `Hide +1s` and all the others fixed.

Having said all that, this is a **totally awesome** extension, so thanks a lot for writing and sharing it!!

**Comment by Mottie** [comment]
Hi @aspiers!

Good points now that it has come to my attention. I think I'll swap the behaviour.

And, I'm glad you're finding this userscript useful. <img title=":_excite:" src="https://cloud.githubusercontent.com/assets/136959/13559383/49d88766-e3d9-11e5-9c0c-9a958bfc03ee.gif">

**Comment by Mottie** [comment]
I've updated the userscript. The font bold didn't change.. it is meant to show which settings would have an effect when toggled. I hope this updated interface is a bit more intuitive. Please let me know what you think.

**Comment by aspiers** [comment]
[**@Mottie**](https://github.com/Mottie) commented on [10 May 2018, 05:59 BST](https://github.com/Mottie/GitHub-userscripts/issues/44#issuecomment-387952282 "2018-05-10T04:59:10Z - Replied by Github Reply Comments"):
> I've updated the userscript. The font bold didn't change.. it is meant to show which settings would have an effect when toggled.

It looks to me like the font *colour* indicates whether settings would have an effect when toggled, not whether the font is bold.  But the way it is right now seems perfect to me!

> I hope this updated interface is a bit more intuitive. Please let me know what you think.

Yes, I think it's *much* clearer now.  Thanks a lot!!

**Comment by Mottie** [comment]
Yeah sorry, I left the bold style on all checked values. I think it looks good too.

And good, I'm glad you think it's clearer. I'll go ahead and close this issue.
