### ISSUE TITLE
(GitHub Sort Content) In pinned repos lists the sort arrow is not displayed initially, and when you click to sort then the arrow is displayed multiple times

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#5]
I've noticed this minor issue in pinned repos lists: (GSC 1.0.3 in FF 48, GM 3.9, win 10):
the sort up/down arrow is not displayed (initially),
and when you click in the area to sort then the sort arrow is displayed multiple times filling the row.

Screenshot from e.g. https://github.com/addyosmani?tab=repositories
![2016-08-20_181648](https://cloud.githubusercontent.com/assets/723651/17832029/50465f4a-6702-11e6-86f2-d9c5eab69eef.jpg)

<br>
PS. Mottie, btw, could you please tell what GIF capture program did you use in order to make the 3 gif screen captures in [here](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content)?

**Comment by Mottie** [comment]
Hi @darkred!

Odd, I can't seem to duplicate the background repeat on pinned repos... I'll go ahead and add a `no-repeat` anyway.

I use [LICEcap](http://www.cockos.com/licecap/) to make the animated screenshots. Sometimes I end up editing them in Photoshop to remove frames or add labels.

**Comment by darkred** [comment]
Thank you. I have also tried it in a clean FF48 profile with only GM and the script, and it occurs too.

**Comment by Mottie** [comment]
Please check and make sure this update fixes the problem.

**Comment by darkred** [comment]
Yes, the update fixes the issue.
It's just that: 
- initially the sort arrow is not displayed:
![2016-08-20_193959](https://cloud.githubusercontent.com/assets/723651/17832539/19653364-670e-11e6-95ea-d33ed3a5a0e8.jpg)
- if you click to sort, then the arrow now is displayed on top of the `Mirrors` link:
![2016-08-20_192512](https://cloud.githubusercontent.com/assets/723651/17832457/10d653e2-670c-11e6-8a09-f7f6f83df249.jpg)
Could you please move the arrow to the left of `All` ?

I'd suggest changing the two lines of your commit
from
`background-position:calc(100% - 5px) center !important; `
to
`background-position:calc(100% - 200px) center !important; `
i.e. in order the arrow to be moved :
![2016-08-20_193601](https://cloud.githubusercontent.com/assets/723651/17832514/64b45c92-670d-11e6-828c-f42a0b34ab3e.jpg)

**Comment by Mottie** [comment]
Ahh, I see why it stopped working... GitHub changed some class names.

**Comment by Mottie** [comment]
Ok, try the script now... I wasn't paying attention initially when I said I couldn't duplicate the problem, it's because I was looking at a user's pinned repos, but the screenshot is from the user's repo tab <img title=":_ derp :" src="https://cloud.githubusercontent.com/assets/136959/13559387/49e2ecce-e3d9-11e5-8a16-73cbfdb7230e.gif"> .

**Comment by darkred** [comment]
I'm really sorry... 
That's the 3rd mistake in a row that I made... (yesterday, posting an issue in the wrong repo, and then ignoring that you told me not to post another issue) and now this...
I feel ashamed...

**Comment by Mottie** [comment]
LOL no worries <img title=":_happy:" src="https://cloud.githubusercontent.com/assets/136959/13559407/7996bb94-e3d9-11e5-9b36-a39832cd3ceb.gif">

**Comment by darkred** [comment]
Yes, the issue is fixed now :+1: 
Thanks for your understanding.
