### ISSUE TITLE
Bulk edit repos

### ISSUE THREAD

**Issue by Bluscream** [Mottie/GitHub-userscripts#51]
Let me explain a little background, recently i was sued by some company and the police didn't tell me more than that it was about some "github repo". In order to be cooperative and increase my chances of the lawsuit being dropped i decided to not delete my account but rather get github premium and make all my repos private until i get information what repo this stuff is about. After purchasing premium i was shocked to see that it doesn't apply to all organisations (i have many repos outsourced) and that i can't bulk edit my stuff. The police was kind enough to tell me that it was one of the repos on my account so i was not worried about the orgs anymore but i had to go through the process of editing the setting of 200+ repos by hand which was kind of a pain in the ass and took me some time but i did it anyway for legal reasons. Now that the case has been dropped i don't need github premium anymore, i had more time and a free head to think about it. I contacted github support about that and asked them why there is no way to bulk edit your stuff because the FAQ states that i will loose all private repos when my gh premium status gets revoked for whatever reason. They said they can't do sh*t and gave me some API endpoints, but i don't feel confident enough to do anything with it so i wanted to ask you if you could help me (and maybe others that want to switch from premium to free and have a bunch of repos on private) by creating something to convert multiple repos at once. I don't really care if it's a "bot" or a website or a userscript.

<details>
<summary>email-convo</summary>

![grafik](https://user-images.githubusercontent.com/3318223/42406282-f14445f8-8193-11e8-81ea-e82966472772.png)

![grafik](https://user-images.githubusercontent.com/3318223/42406298-546f0942-8194-11e8-881e-9812915282e1.png)

</details>

**Comment by Mottie** [comment]
Hi @Bluscream!

I don't have any private repos, so I don't know the process of converting repos from private to public. I wouldn't think it would be difficult. I'm not sure how I can help.

**Comment by Bluscream** [comment]
I can give you temporary access to my account if that helps :)

**Comment by Mottie** [comment]
LOL, no don't do that.

I saw this documentation - https://help.github.com/articles/making-a-private-repository-public/

If you need a userscript to fill in the input, just give me the id of that input.

**Comment by Bluscream** [comment]
> If you need a userscript to fill in the input, just give me the id of that input.

Wouldn't that only make **1** repo public?

**Comment by Mottie** [comment]
Ok, try this:

```js
// ==UserScript==
// @name        GitHub Add Repo Name to Change Visibility
// @version     0.1.2
// @description A userscript that adds your repo name to the visibility dialog
// @license     MIT
// @author      Rob Garrison
// @namespace   https://github.com/Mottie
// @include     https://github.com/*
// @run-at      document-idle
// @require     https://greasyfork.org/scripts/28721-mutations/code/mutations.js?version=597950
// @icon        https://assets-cdn.github.com/pinned-octocat.svg
// ==/UserScript==
(() => {
	"use strict";

	function addName() {
		const name = document.getElementById("rename_field");
		if (name) {
			document.querySelector("form[action$='toggle_permission'] .input-block").value = name.value;
			const btn = document.querySelector("form[action$='toggle_permission'] .btn-danger");
			btn.removeAttribute("disabled");
			btn.removeAttribute("data-disable-invalid");
		}
	}

	document.addEventListener("ghmo:container", addName);
	addName();
})();
```

**Comment by Mottie** [comment]
And yes, it will only work on one repo at a time... I haven't looked to see how to automate the action using the API as I don't have any way to test the code.

**Comment by Bluscream** [comment]
What's your email?
