### ISSUE TITLE
Show Whitespace, enable by default

### ISSUE THREAD

**Issue by clementperon** [Mottie/GitHub-userscripts#53]
Hi,

Is there an option to show the whitespace/tab characters by default ? 

Thanks a lot and Thank you for your scripts !

Clement

**Comment by Mottie** [comment]
Hi @clementperon!

They don't show by default because the script does *a lot* of DOM manipulation. And if you had a huge file, you wouldn't like me very much 😉.

I guess I could add an option to allow you to choose.

**Comment by Mottie** [comment]
Added. Click the tamper/greasy monkey icon in the browser and select "Set GitHub Code White Space" to modify the option.
