### ISSUE TITLE
(GitHub Toggle Issue Comments) "Cannot read property 'textContent' of null" in a specific PR page

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#56]
Using Chrome 69, TM 4.8.5850 beta, GitHub Toggle Issue Comments in 1.2.2. 

The issue is that, in the specific following PR page (I couldn't find any other pages to recreate)
`https://github.com/sindresorhus/refined-github/pull/1526`
the script's filters are non-toggleable and disabled, and I get the following error in Chrome's Console:

```
Execution of script 'GitHub Toggle Issue Comments' failed! Cannot read property 'textContent' of null
```

referring to line 404 of the script which contains:
```
txt = el.textContent.trim();
```

**Comment by Mottie** [comment]
Hi @darkred!

I can't reproduce the error you're mentioning, but I can fortify the code to prevent that error from popping up. Please check the updated userscript to see if it's been fixed.

**Comment by darkred** [comment]
Hey @Mottie 

The issue is reproducible as follows:
with a fresh Chrome browser profile with only  TM 4.8.5850 beta and the script v1.2.2
load `https://github.com/sindresorhus/refined-github/pull/1526`
initially the script runs ok, i.e. the proper filters become bold,
but, when you click the `+1 Comments` filter
then you get the `Uncaught TypeError: Cannot read property 'textContent' of null` error in Console,
and then, when you reload the page, all filters are now non-toggleable and disabled.

----

Yes, with your new version it's now fixed.  Thank you very much!
