### ISSUE TITLE
(GitHub Toggle Issue Comments) In some issue pages, there's an unneeded "1 hidden (from hidden comments)" when 'GitHub Sort Reactions' is also installed

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#57]
Hi again dear @Mottie 

Unfortunately I just found another issue: 
in some issue pages I tried, 
when both "GitHub Toggle Issue Comments" and "GitHub Sort Reactions" are installed,
there's a unneeded `1 hidden (from hidden comments)` under the first post

STR
- with a fresh Chrome browser profile with only TM 4.8.5850 beta and scripts GTIC 1.23 and GSR 0.2.6
- open either 
`https://github.com/Microsoft/vscode/issues/58712` or `https://github.com/Microsoft/vscode/issues/59142` 
- make sure that only the "+1 Comments" filter in GTIC is active: 
notice that in both URLs, when you click it, it becomes "+1 Comments (1 hidden)".
but there's no comment actually hidden (there's no "+1" comment to hide)
- notice that there's a  `1 hidden (from hidden comments)` under the first post.
- *If you disable GSR, then the issue no longer occurs*.

**Comment by Mottie** [comment]
Hi @darkred!

Yeah, the count was from the sort reactions block that was added by the sort reactions userscript. I actually ended up updating both the sort reactions and issue comments userscripts to fix this. Please let me know if you encounter any issues.

**Comment by darkred** [comment]
It's working fine now. Thanks a lot !
