### ISSUE TITLE
(GitHub Diff Links) Add support for Pull Requests

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#6]
Currently it works for commits, such as: https://github.com/zenorocha/sublime-javascript-snippets/commit/a9d8787736c4afe4e8b03bd7fc75cdea47ddd714
but not pull requests: https://github.com/zenorocha/sublime-javascript-snippets/pull/28/files

It would be great if you added support for pull requests to your very useful script.

---

I *think* that the change needed for this is to change line 42 from: 
```
links = $$("#toc ol.content li > a");
```
to
```
links = document.querySelectorAll("#toc ol.content li > a, div.select-menu-list > div > a");
```
and line 65 from
```
if ($("#files.diff-view")) {
```
to
```
if ($("#files.diff-view") || $(".pr-toolbar")) {
```

---

The problems that I still have are: 

1. clicking on the 1st `Next button` in the PR link above,
it navigates you to the 10th file, not the 2nd one.
(All other buttons work ok).

2. Also, in order the buttons tooltips to be ok and not like [this](https://cloud.githubusercontent.com/assets/723651/18535884/904f11a6-7b00-11e6-9b53-508fd2c9800f.jpg)
I think that line 31 
```
txt = txt.substring(txt.lastIndexOf("/") + 1, txt.length);
```
should be combined with: 
```
var regex = /[\s]*\+[\d\+\-\s\−]*([\w\\.]*)/;
txt = txt.match(regex)[1];
```
using something like:
```
if (window.location.href.indexOf("/commit/") !== -1) {
   ...
} else if (window.location.href.indexOf("/pull/") !== -1) {
  ...
}

**Comment by Mottie** [comment]
Hi @darkred!

Sure, I'll look into it.

**Comment by Mottie** [comment]
Ok, try it out! I also added disabled buttons to the first and last files to keep all the buttons aligned 😉.

**Comment by darkred** [comment]
Thanks a lot for the new version! Great!
