### ISSUE TITLE
(GitHub Toggle Issue Comments) Clicking on the avatars in the popup menu no longer toggles the comments from the relevant users

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#60]
Using Chrome 69/Firefox 62 (also in fresh profiles), TM 4.8.5850 beta, GitHub Toggle Issue Comments 1.3.2.

Unfortunately clicking on the avatars in the popup menu no longer toggles the comments from the relevant users.

There's no error in Console.

**Comment by Mottie** [comment]
Thanks for reporting this issue! Fixed in https://github.com/Mottie/GitHub-userscripts/commit/8b65f6b204034860f8fa41473927425c84eeedb7.

**Comment by darkred** [comment]
First of all thank you.

Now it works ok in many pages I tested.
In one page though https://github.com/hayaku/hayaku/issues/303
with the new version, the users list in the popup menu
appears duplicated 2 times (shown with the red arrows) :
![2018-10-05_165914](https://user-images.githubusercontent.com/723651/46539884-647d2800-c8c0-11e8-808a-23724e4523d7.jpg) ![2018-10-05_165959](https://user-images.githubusercontent.com/723651/46539890-6646eb80-c8c0-11e8-9043-3df85d7b6e0d.jpg)


This didn't occur in previous script version 1.3.2.
Tested in a fresh Chrome/FF Profile with only TM beta and the script -screenshots from Firefox- .

**Comment by darkred** [comment]
FYI, the above issue page `https://github.com/hayaku/hayaku/issues/303`
has 6 "x similar comments" and 1 "y hidden comments",
all because of this new GitHub feature: [Hiding repeat comments](https://blog.github.com/changelog/2018-09-24-hiding-repeat-comments/) .

On the other hand, the new issue I describe, i.e. the duplicated users list, doesn't occur in e.g. `https://github.com/isaacs/github/issues/253#issuecomment-422328717`
which has has 2 "x similar comments" and 1 "y hidden comments".

**Comment by Mottie** [comment]
Fixed. I added a hide similar comments toggle as well.

**Comment by darkred** [comment]
Awesome! Thanks 👍
