### ISSUE TITLE
`Github Costom Hotkey` do not work with `safari 12.0.1`

### ISSUE THREAD

**Issue by chenshengzhi** [Mottie/GitHub-userscripts#64]
`Github Costom Hotkey` do not work with `safari 12.0.1`

**Comment by Mottie** [comment]
Hi @chenshengzhi!

All the custom hotkey script does is adds a link with a data-hotkey attribute set with your customizations, e.g.:

```html
<a class="ghch-link" href="https://github.com/openstyles/usercss-meta/pulse" data-hotkey="g p"></a>
```

WIth the above example, pressing <kbd>g</kbd> then <kbd>p</kbd> will activate GitHub's built-in script to go to the link's `href` which is the repo's pulse page.

If this is a specific problem in Safari, then try some of GitHub's other hotkeys (press <kbd>?</kbd> to see them) and if they don't work, then I would report the issue to GitHub support.

**Comment by Neil20170223** [comment]
Thank you for your reply!

Sorry, I did not describe the situation clearly. 
![20181126093257](https://user-images.githubusercontent.com/28893316/48988078-55975100-f15e-11e8-8ef3-4b775ea81755.png)
1. The setting entry do not showing when i tap my avatar. 
2. I try install another scrip `GitHub custom navigation`, but failed again.
3. `TamperMonkey` show they are running.
![20181126093605](https://user-images.githubusercontent.com/28893316/48988162-f7b73900-f15e-11e8-8429-d15c36e1cc77.png)

**Comment by chenshengzhi** [comment]
I test using script:
```
// ==UserScript==
// @name         Test
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      *://*github.com/*
// @include      *://*.google*/*
// @grant        none
// ==/UserScript==

(function () {
    console.log("test test test test test ");
})()
```
I see the log in `Google`, but not in `Github`.
@Mottie can you help me? Thanks!

**Comment by Mottie** [comment]
I don't own any apple products, so I'm not able to use safari... either way, this sounds like it's an issue with Tampermonkey. Please report the problem here: https://github.com/Tampermonkey/tampermonkey/issues

**Comment by chenshengzhi** [comment]
OK, Thank you very much.
