### ISSUE TITLE
GitHub issue show status: Implemented by GitHub

### ISSUE THREAD

**Issue by salmanulfarzy** [Mottie/GitHub-userscripts#67]
https://blog.github.com/changelog/2019-01-04-sticky-coversation-headers/

> The title and status on issues and pull request conversations now persists in a sticky header – giving you more context when scrolling through long conversation threads.

**Comment by Mottie** [comment]
Hi @salmanulfarzy!

Thanks! I'll add a deprecated note on that script soon.

**Comment by rybak** [comment]
It would seem from [the history of `github-issue-show-status.user.js`](https://github.com/Mottie/GitHub-userscripts/commits/master/github-issue-show-status.user.js) that the deprecation note hasn't been added yet.
