### ISSUE TITLE
GitHub table of contents not working in Firefox with Greasemonkey

### ISSUE THREAD

**Issue by hckr** [Mottie/GitHub-userscripts#69]
The following shows up in Firefox's developer console after installation of your "GitHub table of contents" userscript in Greasemonkey:
![screenshot_20190116_014216](https://user-images.githubusercontent.com/1078650/51219250-4481e980-1930-11e9-8a02-851a27eb48ff.png)

That's weird, because there is a `@grant GM_addStyle` in the code...

**Comment by hckr** [comment]
Wow, thanks for the quick reply.

>Greasemonkey changed its api and made it non-backwards compatible.

:disappointed:

>but adding two different `@grant` entries for each method is troublesome

If it solves the issue, it definetely will be helpful for people who'd like to use your userscripts. I don't think it's worth to fight with Greasemonkey developers :stuck_out_tongue_closed_eyes:

**Comment by Mottie** [comment]
The TOC userscript is now compatible with GM4.

**Comment by hckr** [comment]
Great, thanks!
