### ISSUE TITLE
please document where bugs should be reported

### ISSUE THREAD

**Issue by aspiers** [Mottie/GitHub-userscripts#7]
Just discovered this awesome gold-mine of userscripts - many thanks for sharing these!  Please can you update the README.md to clarify where we should send bug reports?  I'm assuming it's either right here in this repo's issue tracker, or as discussions on Greasy Fork, but it would be helpful to document this for the benefit of all future users.  Thanks!

**Comment by Mottie** [comment]
Hi @aspiers!

Sure thing! Reporting issues here would be ideal.

**Comment by aspiers** [comment]
Great, thanks! I agree that Greasy Fork is not as good for tracking issues.

**Comment by Mottie** [comment]
I'll start working on the fixes later today ⏳.

**Comment by aspiers** [comment]
Awesome, thanks :-)  No rush from my side.  I've submitted them as individual issues here; hope that helps.
