### ISSUE TITLE
(GitHub Custom Navigation) the Greasyfork mirror version was not updated after my commit

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#70]
Hi @Mottie 

I just pushed this commit https://github.com/Mottie/GitHub-userscripts/commit/a3e51347dcc0e9884cc95e5f352e281211346442 in order to update the Blog site URL ( github.blog )
(bumping the script version of course)
but unfortunately the script was not updated in [GreasyFork](https://greasyfork.org/scripts/20830).

Have you not set up a webhook on GitHub for GF ?
Just wanted to inform you.

**Comment by Mottie** [comment]
Hi @darkred!

Yes, there is a webhook in place. I believe it won't update unless the package.json version has been modified. I'll take care of it.

**Comment by darkred** [comment]
It's updated now. 👍
