### ISSUE TITLE
Github Download Zip stopped working due to GH changes

### ISSUE THREAD

**Issue by CollinChaffin** [Mottie/GitHub-userscripts#72]
Hey @Mottie I just saw the available update to this "Github Download Zip" script and installed it, and despite it working as before in the commits links, for some reason now on the most important (to me) main repo page download button ZIP, it no longer is adding the icon nor changing the link so the default `-master.zip` downloads. With this being the main link others probably have gotten spoiled with using this for is there any chance (other than my original above enhancement discussion) take a quick look at fixing current to get it at least back up and running again? Thanks!

EDIT:  Fix identified and tested. PR forthcoming.

**Comment by CollinChaffin** [comment]
PR #73 Created

**Comment by Mottie** [comment]
Awesome, thanks!
