### ISSUE TITLE
(GitHub download zip) multiple buttons on navigating back in commits

### ISSUE THREAD

**Issue by jerone** [Mottie/GitHub-userscripts#74]
I navigate a lot on GitHub, in commits for example. But when navigating back, your "GitHub download zip" userscript appends another download button.

Steps to reproduce:
1. Open commits: https://github.com/Mottie/GitHub-userscripts/commits/master
2. Navigate to an older page.
3. Go back to the previous page by using the back button in your browser.
4. See a second download button appear.

![image](https://user-images.githubusercontent.com/55841/52368392-93620100-2a4e-11e9-9338-39952490c2ca.png)

**Comment by Mottie** [comment]
Hi @jerone!

Thanks for letting me know, I'll look into this ASAP.

**Comment by Mottie** [comment]
Ugh, sorry! I've been short on time. I'll try to find some time to work on this on the weekend.

**Comment by jerone** [comment]
@Mottie No hurry.

**Comment by Mottie** [comment]
Whew. All done! 😸
