### ISSUE TITLE
github-files-filter.user.js not working after 'go back' from a next page

### ISSUE THREAD

**Issue by k-choi** [Mottie/GitHub-userscripts#77]
Filters don't work when you open a new page and then come back.

Steps to reproduce:
1. after setting up a filter on a repo page,
1. click a file to see the contents,
1. and come back to the repo page using 'go back'
1. filters would stop working

**Comment by Mottie** [comment]
Hi @k-choi!

Thanks for reporting this problem. I'll take a look at this soon.

**Comment by k-choi** [comment]
Thank you so much!
