### ISSUE TITLE
Raw links no longer working

### ISSUE THREAD

**Issue by CollinChaffin** [Mottie/GitHub-userscripts#78]
Hi @Mottie Rob!

Hey when you get a min could you take a look at the raw links userscript as it suddenly is no longer working.  I'm not sure if the element id changed like recently happened with the other one but my CSS/Ajax skills are admittedly not quite what I wish they were or I would have already put my finger on it.  This one is definitely in the top 3 believe it or not of the ones I rely on most, so hopefully it's the quick fix I'm suspecting it is.

Thanks so much!

**Comment by Mottie** [comment]
Hi @CollinChaffin!

It's a tiny bit more complicated than I thought. I almost finished work on it this morning, but now I gotta run. I'll get a fix out later tonight.

**Comment by CollinChaffin** [comment]
No prob @Mottie I really appreciate you looking at it so quickly and I'm sure you'll wrap it up soon enough!

**Comment by Mottie** [comment]
Fixed in https://github.com/Mottie/GitHub-userscripts/commit/ce7294703f8c963ef4a1a89c5b6e1c988762a328.

**Comment by CollinChaffin** [comment]
Confirmed looks great thanks so much Rob!
