### ISSUE TITLE
toggle expanders also starts to edit the PR title

### ISSUE THREAD

**Issue by aspiers** [Mottie/GitHub-userscripts#8]
As reported at https://greasyfork.org/en/forum/discussion/11753/x; filing here to ease tracking of resolution :-)  Thanks!

**Comment by Mottie** [comment]
Hi @aspiers!

Do you have an example page that I can look at? I know it won't work for me as I won't be a collaborator, but the layout of the page may help me isolate this issue.

**Comment by aspiers** [comment]
Sure: try this one: https://github.com/crowbar/crowbar-core/pull/575/commits

**Comment by Mottie** [comment]
Greats thanks! It should be all fixed now!

**Comment by aspiers** [comment]
Confirmed it works - awesome!
