### ISSUE TITLE
('GitHub Search Autocomplete' with 'GitHub Dark userstyle') the popup becomes transparent and the text on its left remains black 

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#83]
* **Browser**: Chrome 74.0.3729.157/Firefox 66.0.5, Stylus 1.5.3, GitHub Dark 1.21.57
* **Operating System**:Windows 10
* **Link to page with the issue**: e.g. https://github.com/StylishThemes/GitHub-Dark/issues
* **Screenshot**: (comparison)
with the userstyle:
![2019-05-19_225356](https://user-images.githubusercontent.com/723651/57987368-29afb500-7a89-11e9-8f0b-5c83e857e6a3.jpg)
without the userstyle:
![2019-05-19_225445](https://user-images.githubusercontent.com/723651/57987369-2ae0e200-7a89-11e9-8282-11ad7ee51e46.jpg)

Using the [GitHub Search Autocomplete](https://greasyfork.org/en/scripts/28592-github-search-autocomplete) v1.0.1 userscript with Tampermonkey 4.9.5941 beta.

The issue is that with the style, the popup for this userscript becomes transparent and the text on its left is mostly unreadable (black) when unfocused.
Could you please check this out, @Mottie ?

STR
- Open https://github.com/StylishThemes/GitHub-Dark/issues
- focus the issues search box
- type e.g. `in:` so that the userscript popup appears.

**Comment by Mottie** [comment]
Hi @darkred!

Thanks for letting me know. GitHub has been changing a lot of class names. I haven't been keeping track, so I appreciate the report!

**Comment by Mottie** [comment]
I only "partially" fixed it in that the library being used doesn't allow you to customize the highlighted class name, so it's stuck with the default blue color, for now. When & if I find the time & motivation, I'll replace the jQuery dependent autocomplete library with a plain JS one that'll hopefully allow custom class names.

**Comment by darkred** [comment]
Thank you for your quick response 🙂
