### ISSUE TITLE
(GitHub Issue Comments) An empty image placeholder is displayed in the OP when hiding +1 comments

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#84]
STR
With Chrome 74/Firefox 67 and only Tampermonkey beta 4.9.5941 and 'GitHub Issue Comments' v1.3.7 :
- open https://github.com/StylishThemes/GitHub-Dark/issues/946
- toggle the '+1 Comments' in the script's menu
- check the bottom of the OP and notice the empty placeholder:
![2019-05-24_014838](https://user-images.githubusercontent.com/723651/58291481-37857300-7dc6-11e9-969f-f193851e2c38.jpg)

Could you please take a look, @Mottie ?

---

As a sidenote, the `+1 Comments` doesn't show up as active/available filter in the above issue page when enabling the global "Toggle items" filter, even though it has content.

**Comment by Mottie** [comment]
Hi @darkred!

It looks like GitHub moved their emoji assets. As for the +1 comments showing up... it seems intermittent. Sometimes I see it inactive and other times it's active. I'll check into it when I have time this weekend.

**Comment by Mottie** [comment]
Oops

**Comment by Mottie** [comment]
The +1 entry seems to consistently show up now. I didn't change anything, but now I can't reproduce the problem.

**Comment by darkred** [comment]
Yes, it shows up consistently, I confirm.

Unofortunately the other issue still occurs:

> As a sidenote, the `+1 Comments` doesn't show up as active/available filter in the above issue page when enabling the global "Toggle items" filter, even though it has content.

**Comment by darkred** [comment]
Fixed via a commit in #105 .
