### ISSUE TITLE
[ToggleExpanders] Shift+click not working when comparing branches/tags

### ISSUE THREAD

**Issue by malnvenshorn** [Mottie/GitHub-userscripts#87]
At the moment toggling only toggling with ctrl+shift+click is working when comparing branches/tags, e.g. https://github.com/torvalds/linux/compare/v5.2-rc1...v5.2-rc2

Consider this change to enable shift+click within that view

```
const parentNode = stateNode.closest(modKey ?
	".container, .js-discussion" :
	".commit-group, .js-timeline-item, .timeline-commits"
);
```

It would also be great to be able to toggle file diffs.

**Comment by Mottie** [comment]
Hi @malnvenshorn!

That sounds reasonable, I'll look into it!
