### ISSUE TITLE
[Feature Request] Hotkey for Insert Code 

### ISSUE THREAD

**Issue by SmartManoj** [Mottie/GitHub-userscripts#89]
Hotkey for Insert Code  like Stackoverflow
Ctrl K for code
Ctrl L for link

**Comment by Mottie** [comment]
Hi @SmartManoj!

It looks like <kbd>Ctrl</kbd>+<kbd>k</kbd> is already defined as a hotkey to insert a link. So, I can provide you with a simple very specific alternative to get that to work for you. 

```js
// ==UserScript==
// @name        GitHub Markdown Editor Hotkeys
// @version     0.1.0
// @description A userscript that changes the markdown editor code & link hotkeys
// @license     MIT
// @author      Rob Garrison
// @namespace   https://github.com/Mottie
// @include     https://github.com/*
// @run-at      document-idle
// @grant       none
// @icon        https://github.githubassets.com/pinned-octocat.svg
// ==/UserScript==
(() => {
	"use strict";

	function attr(el, key, label) {
		el.setAttribute("hotkey", key);
		el.setAttribute("aria-label", label);
	}

	function init(event) {
		if (document.querySelector("markdown-toolbar")) {
			document.querySelectorAll("md-code").forEach(el => {
				attr(el, "k", "Insert code <ctrl+k>");
			});
			document.querySelectorAll("md-link").forEach(el => {
				attr(el, "l", "Add a link <ctrl+l>");
			});
		}
	}

	document.addEventListener("pjax:end", init);
	init();

})();
```

In case you didn't notice, the [custom hotkey script](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-custom-hotkeys) allows you to add custom hotkeys that change the url, so it wouldn't have worked in this case.

**Comment by SmartManoj** [comment]
Off topic:
Why would you use all openuserjs , GreasyFork , github and how you maintain them ?

**Comment by Mottie** [comment]
Most users of userscripts would search OpenUserJs & GreasyFork for scripts. And both of those sites allow using GitHub commit hooks that auto-update the scripts on their site, so maintenance is minimal. Although, I did notice that after renaming one script, I now have to manually update it on OpenUserJs.

**Comment by SmartManoj** [comment]
How would you test the script and host it in github.
I am currently doing like [this](https://stackoverflow.com/a/56294467).

**Comment by Mottie** [comment]
I guess I'm old school, I copy-paste. I don't think everything needs to automated.

**Comment by SmartManoj** [comment]
> Hi @SmartManoj!
> 
> It looks like Ctrl+k is already defined as a hotkey to insert a link. So, I can provide you with a simple very specific alternative to get that to work for you.
> 
> ```js
> // ==UserScript==
> // @name        GitHub Markdown Editor Hotkeys
> // @version     0.1.0
> // @description A userscript that changes the markdown editor code & link hotkeys
> // @license     MIT
> // @author      Rob Garrison
> // @namespace   https://github.com/Mottie
> // @include     https://github.com/*
> // @run-at      document-idle
> // @grant       none
> // @icon        https://github.githubassets.com/pinned-octocat.svg
> // ==/UserScript==
> (() => {
>   "use strict";
> 
>   function attr(el, key, label) {
>     el.setAttribute("hotkey", key);
>     el.setAttribute("aria-label", label);
>   }
> 
>   function init(event) {
>     if (document.querySelector("markdown-toolbar")) {
>       document.querySelectorAll("md-code").forEach(el => {
>         attr(el, "k", "Insert code <ctrl+k>");
>       });
>       document.querySelectorAll("md-link").forEach(el => {
>         attr(el, "l", "Add a link <ctrl+l>");
>       });
>     }
>   }
> 
>   document.addEventListener("pjax:end", init);
>   init();
> })();
> ```
> 
> In case you didn't notice, the [custom hotkey script](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-custom-hotkeys) allows you to add custom hotkeys that change the url, so it wouldn't have worked in this case.

<ctrl+l> goes to address bar

**Comment by SmartManoj** [comment]
Ctrl L goes to address bar sometimes

**Comment by Mottie** [comment]
This userscript uses GitHub's method to apply hotkeys - meaning all this userscript does is adds a `hotkey="x"` to a link.

I don't think their code overrides browser specific shortcuts. I have <kbd>F1</kbd> set to open the hotkeys settings modal (by default), but lately I haven't gotten it to do anything but open the Google Chrome help page.

**Comment by SmartManoj** [comment]
> Ctrl L goes to address bar sometimes

But sometimes only

**Comment by SmartManoj** [comment]
> This userscript uses GitHub's method to apply hotkeys - meaning all this userscript does is adds a `hotkey="x"` to a link.
> 
> I don't think their code overrides browser specific shortcuts. I have F1 set to open the hotkeys settings modal (by default), but lately I haven't gotten it to do anything but open the Google Chrome help page.

Works Fine for me

**Comment by SmartManoj** [comment]
```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://github.com/Mottie/GitHub-userscripts/issues/89
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
document.onkeydown=function(e){
    if (e.key=='F1'){
        e.preventDefault();
        alert(2);

}
}
})();
```
