### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by NoamDev** [Mottie/GitHub-userscripts#90]
I do not understand how to install this wonderful tool..
Can you help?

**Comment by jerone** [comment]
https://github.com/Mottie/GitHub-userscripts#installation

**Comment by Mottie** [comment]
Hi @NoamDev!

I hope you've figured out how to install and use these scripts. If you need further assistance, please feel free to continue the conversation in this issue. I'm going to close it, but that doesn't mean I won't respond.
