### ISSUE TITLE
(GitHub code show whitespace) button alignment in pr files

### ISSUE THREAD

**Issue by jerone** [Mottie/GitHub-userscripts#91]
Button [GitHub code show whitespace](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-show-whitespace) (1.2.9) is not playing nice in PR files:

![image](https://user-images.githubusercontent.com/55841/60544285-c320e680-9d18-11e9-98a5-d0c9e3128c7a.png)

Keep up the great work.

**Comment by Mottie** [comment]
Hi @jerone!

Thanks for letting me know. I'll have it fixed ASAP!

**Comment by jerone** [comment]
Thanks @Mottie. Fixed perfectly as always.
