### ISSUE TITLE
Auto filling numbering list 

### ISSUE THREAD

**Issue by SmartManoj** [Mottie/GitHub-userscripts#93]
1. one
two

**Comment by SmartManoj** [comment]
Is it possible to auto number ?

**Comment by Mottie** [comment]
Hi @SmartManoj!

Auto number what? If you're using markdown, then start with any number followed by a period:

```
1. Entry one
1. Entry two
1. The numbers will become sequential
```

1. Entry one
1. Entry two
1. The numbers will become sequential

**Comment by SmartManoj** [comment]
We have to 1.  for all

**Comment by Mottie** [comment]
No, any number, but start with one:

```
1. Entry one
4565. Entry two
6347357. Entry three
```

1. Entry one
4565. Entry two
6347357. Entry three

You'll start with the number you enter first:

```
42. Entry one
4565. Entry two
6347357. Entry three
```

42. Entry one
4565. Entry two
6347357. Entry three

**Comment by Mottie** [comment]
See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists

**Comment by SmartManoj** [comment]
We have to enter <number>. for all

**Comment by Mottie** [comment]
Yes. Or, a right parenthesis `)`. That is how Markdown defines ordered lists.

Try out this tutorial - https://commonmark.org/help/tutorial/06-lists.html

The https://commonmark.org/ website also includes the spec and a forum to discuss markdown.

**Comment by SmartManoj** [comment]
When Press enter, auto fill the next number

**Comment by SmartManoj** [comment]
Like Shift Enter in Stackoverflow

**Comment by Mottie** [comment]
This is now built-into GitHub.
