### ISSUE TITLE
[bug] Code colors allows overflow in all code blocks

### ISSUE THREAD

**Issue by jhpratt** [Mottie/GitHub-userscripts#96]
[These lines are in question](https://github.com/Mottie/GitHub-userscripts/commit/b8830e754c1a1d9fdd3a7ffc07487cef6b56ba51#diff-be55d55f33e883538d4369f2b03f4db8R31-R32)

This single declaration allows `overflow` on _all_ codeblocks, such as on [this page](https://github.com/tc39/proposal-nullish-coalescing) (at least on a 1080 display).

![example](https://user-images.githubusercontent.com/3161395/61914581-113b9b00-af0f-11e9-8324-dfb1056de8c9.png)

What is the intent of this CSS? I've currently disabled this userscript due to this issue.

**Comment by Mottie** [comment]
Hi @jhpratt!

Yep, oops!! I have a [code wrap userscript](https://greasyfork.org/en/scripts/18789-github-toggle-code-wrap) installed, so I didn't notice. I'll have this fixed ASAP.

**Comment by Mottie** [comment]
I set the overflow to be visible because the code color swatch is now clickable. It opens a popup containing the color in different formats.

**Comment by jhpratt** [comment]
Nice work! Thanks for the _extremely_ fast update.
