### ISSUE TITLE
[Question] Keep navbar when scrolled down?

### ISSUE THREAD

**Issue by Bluscream** [Mottie/GitHub-userscripts#98]
My navbar keeps being replaced with some other bar whenever is scroll down. i would like to be able to see atleast my notifications icon at all times though

![](https://i.imgur.com/4S8lAH7.gif)

Can this be easily "fixed"?

**Comment by Mottie** [comment]
Hi @Bluscream!

That bar was added by GitHub so you always know the status of the issue or PR.

If you're using Stylus, then we also have a UserCSS named [GitHub-FixedHeader](https://github.com/StylishThemes/GitHub-FixedHeader) that keeps the navbar always visible.

**Comment by Bluscream** [comment]
Thank you, works like a charm :)
