### ISSUE TITLE
Sort Does Not Work on Org Repo List

### ISSUE THREAD

**Issue by AdrianTP** [Mottie/GitHub-userscripts#99]
About: https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content

Steps to Reproduce:
1. Go to https://github.com/jquery (as in the example gif in the [GitHub-sort-content wiki page](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content))
2. Notice the lack of the sort indicator

Notes:
It still works in the People tab...

**Comment by Mottie** [comment]
Hi @AdrianTP!

Thanks, I'll work on this soon.

**Comment by Mottie** [comment]
Please review the [change log](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content#version-300-2019-09-01) for this update.

**Comment by AdrianTP** [comment]
@Mottie Lovely, thanks so much for the quick turnaround!
